workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.27.3
      xcode: 16.2
    scripts:
      - echo "=== Starting build ==="
      - flutter --version
      - flutter doctor
      - echo "=== Cleaning project ==="
      - flutter clean
      - echo "=== Getting dependencies ==="
      - flutter pub get
      - echo "=== Building iOS ==="
      - flutter build ios --simulator --verbose
      - echo "=== Build completed ==="
    artifacts:
      - build/ios/iphonesimulator/Runner.app