workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.27.3
      xcode: 16.2
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --simulator --release
    artifacts:
      - build/ios/iphonesimulator/Runner.app