name: ecommercecourse
description: "Ecommerce App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # الأساسيات
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  jiffy: ^6.2.2
  http: ^1.4.0

  # معالجة الصور
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+5

  # الرسوم المتحركة
  show_up_animation: ^2.0.0
  auto_animated: ^3.1.0



  # Firebase
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3

  # التخزين المحلي
  sqflite: ^2.2.8+4
  shared_preferences: ^2.1.1
  path: ^1.9.0

  # QR Code
  qr_flutter: ^4.1.0
  scan: ^1.6.0

  # القوائم والواجهات
  grouped_list: ^5.1.2
  url_launcher: ^6.2.1
  dropdown_search: ^5.0.6
  badges: ^3.1.1

  # الأيقونات
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0

  # أدوات مساعدة
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  google_sign_in: ^6.1.3
  device_preview: ^1.2.0
  responsive_builder: ^0.7.0
  image_pickers: ^2.0.4+1
  flutter_otp_text_field: ^1.4.0+2
  lottie: ^3.0.0
  flutter_local_notifications: ^18.0.1
  timelines: ^0.1.0
  flutter_ringtone_player: ^4.0.0+3
  rating_dialog: ^2.0.4
  iconsax_flutter: ^1.0.0
  shimmer: ^2.0.0
  convex_bottom_bar: ^3.0.0
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  timeago: ^3.1.0
  liquid_pull_to_refresh: ^3.0.0
  get_storage: ^2.0.3
  drop_down_list: ^0.0.4
  file_picker: ^10.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  visibility_detector: ^0.4.0
  photo_view: ^0.14.0
  flutter_image_compress: ^2.0.4
  video_compress: ^3.1.2
  path_provider: ^2.1.1
  pin_code_fields: ^7.4.0
  device_info_plus: ^9.1.0
  pinput: ^3.0.1
  provider: ^6.0.5

  # ZegoCloud - الإصدارات المتوفرة والمتوافقة
  zego_zim: ^2.9.0
  zego_uikit_signaling_plugin: ^2.8.13
  zego_express_engine: ^3.14.5

  # الصوت والملفات
  record: ^5.0.4
  open_file: ^3.3.2
  dio: ^5.3.2
  flutter_pdfview: ^1.3.2
  audioplayers: ^5.2.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
