platform :ios, '13.0'

target 'Runner' do
  use_frameworks!use_modular_headers!
  flutter_root = File.dirname(File.realpath(__FILE__))
  require File.join(flutter_root, 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_root)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
